# Generated by Django 5.0.4 on 2024-07-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0004_alter_categoryimage_image_alter_product_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
