# Generated by Django 5.0.4 on 2024-07-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0005_categoryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_panel.product'),
        ),
    ]
