# Generated by Django 5.0.4 on 2024-07-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0007_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin_panel.productdetail'),
        ),
    ]
