# Generated by Django 5.0.4 on 2024-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0008_remove_wishlist_products_wishlist_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='color',
            field=models.CharField(choices=[('BL', 'Blue'), ('GR', 'Green'), ('RD', 'Red'), ('YL', 'Yellow'), ('BK', 'Black'), ('WH', 'White'), ('OR', 'Orange')], default='BK', max_length=2),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=2),
        ),
    ]
