# Generated by Django 5.0.4 on 2024-07-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0009_categoryimage_color_categoryimage_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin_panel.product'),
        ),
    ]
