# Generated by Django 5.0.4 on 2024-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0011_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_note',
            field=models.TextField(default='', max_length=500),
        ),
    ]
