# Generated by Django 5.0.4 on 2024-07-30 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0012_checkout_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
